// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.2
// Source: nursor_rpc.proto

package server

import (
	"nursor-envoy-rpc/internal/logic"
	"nursor-envoy-rpc/internal/svc"
	"nursor-envoy-rpc/protobuf/extproc"
)

type ExternalProcessorServer struct {
	svcCtx *svc.ServiceContext
	extproc.UnimplementedExternalProcessorServer
}

func NewExternalProcessorServer(svcCtx *svc.ServiceContext) *ExternalProcessorServer {
	return &ExternalProcessorServer{
		svcCtx: svcCtx,
	}
}

// 双向流式 RPC，处理 HTTP 请求和响应
func (s *ExternalProcessorServer) Process(stream extproc.ExternalProcessor_ProcessServer) error {
	l := logic.NewProcessLogic(stream.Context(), s.svcCtx)
	return l.Process(stream)
}
