// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.2
// Source: nursor_rpc.proto

package externalprocessor

import (
	"context"

	"nursor-envoy-rpc/protobuf/extproc"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	BodyMutation       = extproc.BodyMutation
	BodyResponse       = extproc.BodyResponse
	CommonResponse     = extproc.CommonResponse
	HeaderMutation     = extproc.HeaderMutation
	HeaderValue        = extproc.HeaderValue
	HeaderValueOption  = extproc.HeaderValueOption
	HeadersResponse    = extproc.HeadersResponse
	HttpBody           = extproc.HttpBody
	HttpHeaders        = extproc.HttpHeaders
	HttpTrailers       = extproc.HttpTrailers
	ImmediateResponse  = extproc.ImmediateResponse
	ProcessingRequest  = extproc.ProcessingRequest
	ProcessingResponse = extproc.ProcessingResponse
	TrailersResponse   = extproc.TrailersResponse

	ExternalProcessor interface {
		// 双向流式 RPC，处理 HTTP 请求和响应
		Process(ctx context.Context, opts ...grpc.CallOption) (extproc.ExternalProcessor_ProcessClient, error)
	}

	defaultExternalProcessor struct {
		cli zrpc.Client
	}
)

func NewExternalProcessor(cli zrpc.Client) ExternalProcessor {
	return &defaultExternalProcessor{
		cli: cli,
	}
}

// 双向流式 RPC，处理 HTTP 请求和响应
func (m *defaultExternalProcessor) Process(ctx context.Context, opts ...grpc.CallOption) (extproc.ExternalProcessor_ProcessClient, error) {
	client := extproc.NewExternalProcessorClient(m.cli.Conn())
	return client.Process(ctx, opts...)
}
